# bundle exec jekyll serve --host=0.0.0.0

title: MycilaDS18
description: ESP32 / Arduino Library for Dallas / Maxim DS18B20 sensor using RMT peripheral
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
